// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykodpjvlwdwxgcmtsmtu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlrb2RwanZsd2R3eGdjbXRzbXR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMDgxNTEsImV4cCI6MjA3MDY4NDE1MX0.N_lXm4wxuymIlrStHIWssnTjdS7-FJfSJL698LY1iq4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});